# Generated by Django 5.0.6 on 2024-06-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='shared_users',
        ),
    ]
