# Generated by Django 5.0.6 on 2024-06-28 13:07

import snippet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=snippet.models.user_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="snippet",
            name="code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
